### PR TITLE
[docs] GETTING_STARTED OTel section copyedits

### PR DESCRIPTION
**Pull request by chalin**
Minimal copyedits to the OTel section of the Getting started page.

/cc @theletterf @svrnm @cartermp

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
Thanks!

**Comment by theletterf** [comment]
Looks good to me!

**Comment by atreat** [comment]
Thanks for these, appreciate you checking out the project!

**Comment by atreat** [comment]
This has been merged internally! You'll see these updates in the GETTING_STARTED doc on main.

**Pull request closed without merging**
